import { buildCard } from "../cardModel";
import { FONT_MONO, RADII, SHADOW } from "../theme";

/* Findings report — slide-over assembled entirely from live run state
   (hypotheses + loaded dataset metadata), via the same buildCard deriver the
   panel uses. The narrative characterization prose is produced server-side and
   written to the on-disk Markdown report; surfacing it here needs a report-
   content endpoint and is a deliberate fast-follow (see note in the drawer). */

function Verdict({ state, t }) {
  const map = {
    confirmed: { c: t.confirmed, l: "Confirmed", i: "✓" },
    uncertain: { c: t.uncertain, l: "Uncertain", i: "?" },
    rejected:  { c: t.rejected,  l: "Rejected",  i: "–" },
  };
  const v = map[state]; if (!v) return null;
  return <span style={{ display: "inline-flex", alignItems: "center", gap: 4, fontSize: 10, fontWeight: 700, letterSpacing: "0.05em", textTransform: "uppercase", color: v.c }}>{v.i} {v.l}</span>;
}

const Id = ({ children, t }) => <span style={{ fontFamily: FONT_MONO, fontSize: 11, fontWeight: 600, color: t.textMuted }}>{children}</span>;
const SecH = ({ children, t }) => <h2 style={{ margin: "0 0 12px", fontSize: 13, fontWeight: 700, letterSpacing: "0.02em", color: t.textPrimary }}>{children}</h2>;
const Count = ({ n, color }) => <span style={{ fontFamily: FONT_MONO, fontSize: 12, color, marginLeft: 6 }}>{n}</span>;

export default function ReportDrawer({ hypotheses, datasets, colorMode, onClose, theme: t }) {
  const cards = hypotheses.map(buildCard);
  const confirmed = cards.filter((c) => c.state === "confirmed");
  const uncertain = cards.filter((c) => c.state === "uncertain");
  const rejected  = cards.filter((c) => c.state === "rejected");
  const incomplete = cards.some((c) => ["pending", "testing"].includes(c.state));
  const withTrans = confirmed.filter((c) => c.translational);

  return (
    <div onClick={onClose} style={{ position: "fixed", inset: 0, zIndex: 100, background: "rgba(0,0,0,.45)", display: "flex", justifyContent: "flex-end" }}>
      <div onClick={(e) => e.stopPropagation()} style={{ width: "min(640px, 92vw)", height: "100%", background: t.appBg, borderLeft: `1px solid ${t.border}`, boxShadow: SHADOW[colorMode].lg, display: "flex", flexDirection: "column" }}>

        {/* bar */}
        <div style={{ flex: "none", height: 52, display: "flex", alignItems: "center", gap: 10, padding: "0 18px", borderBottom: `1px solid ${t.border}`, background: t.sidebarBg }}>
          <span style={{ fontSize: 13, fontWeight: 600, color: t.textPrimary }}>📄 Findings report</span>
          {incomplete && (
            <span style={{ fontSize: 10.5, color: t.uncertain, background: t.uncertainSoft, border: `1px solid ${t.uncertainBd}`, borderRadius: 99, padding: "2px 8px" }}>⚠ Incomplete · resumable</span>
          )}
          <button onClick={onClose} style={{ marginLeft: "auto", width: 30, height: 30, display: "grid", placeItems: "center", background: "transparent", border: `1px solid ${t.border}`, borderRadius: RADII.md, color: t.textSecondary, cursor: "pointer", fontSize: 14 }}>✕</button>
        </div>

        <div style={{ flex: 1, overflowY: "auto", padding: "22px 26px" }}>
          <div style={{ fontFamily: FONT_MONO, fontSize: 11, color: t.textMuted, marginBottom: 6 }}>
            {datasets.length} cohort{datasets.length === 1 ? "" : "s"} · {datasets.reduce((a, d) => a + (d.sample_count || 0), 0)} samples
          </div>
          <h1 style={{ margin: "0 0 22px", fontSize: 20, fontWeight: 700, letterSpacing: "-0.01em", color: t.textPrimary, lineHeight: 1.25 }}>
            Autonomous discovery run — findings
          </h1>

          {/* characterization — deferred prose */}
          <section style={{ marginBottom: 26 }}>
            <SecH t={t}>Characterization</SecH>
            <p style={{ margin: 0, fontSize: 12.5, lineHeight: 1.6, color: t.textMuted, fontStyle: "italic" }}>
              The narrative characterization is generated by the PI agent and written to the on-disk
              Markdown report. Surfacing it inline is a planned follow-up (report-content endpoint).
            </p>
          </section>

          {/* confirmed */}
          <section style={{ marginBottom: 26 }}>
            <SecH t={t}>Confirmed axes<Count n={confirmed.length} color={t.confirmed} /></SecH>
            {confirmed.length === 0 && <div style={{ fontSize: 12.5, color: t.textMuted }}>None confirmed.</div>}
            {confirmed.map((c) => (
              <div key={c.id} style={{ padding: "12px 14px", marginBottom: 8, background: t.cardBg, border: `1px solid ${t.border}`, borderLeft: `3px solid ${t.confirmed}`, borderRadius: RADII.md }}>
                <div style={{ display: "flex", alignItems: "flex-start", gap: 8, marginBottom: 8 }}>
                  <Id t={t}>{c.id}</Id>
                  <span style={{ flex: 1, fontSize: 13, fontWeight: 500, color: t.textPrimary, lineHeight: 1.4 }}>{c.statement}</span>
                  <Verdict state="confirmed" t={t} />
                </div>
                <div style={{ display: "flex", flexWrap: "wrap", gap: "4px 16px", fontSize: 11.5, color: t.textSecondary }}>
                  <span>method families <b style={{ fontFamily: FONT_MONO }}>{c.methodFamilies.length}</b></span>
                  <span>replicated <b style={{ fontFamily: FONT_MONO }}>{c.replication.filter((r) => r.status === "ok").length}/{c.replication.length}</b></span>
                  {c.metaFDR && <span>meta-FDR <b style={{ fontFamily: FONT_MONO }}>{c.metaFDR}</b></span>}
                  {c.heterogeneity && <span>heterogeneity <b style={{ fontFamily: FONT_MONO }}>{c.heterogeneity}</b></span>}
                </div>
              </div>
            ))}
          </section>

          {/* uncertain + rejected */}
          <section style={{ marginBottom: 26, display: "grid", gridTemplateColumns: "1fr 1fr", gap: 18 }}>
            <div>
              <SecH t={t}>Held uncertain<Count n={uncertain.length} color={t.uncertain} /></SecH>
              {uncertain.length === 0 && <div style={{ fontSize: 12, color: t.textMuted }}>None.</div>}
              {uncertain.map((c) => (
                <div key={c.id} style={{ fontSize: 12, color: t.textSecondary, marginBottom: 8, lineHeight: 1.5 }}>
                  <Id t={t}>{c.id}</Id> {c.statement}
                  {c.heterogeneity && <div style={{ fontSize: 10.5, color: t.uncertain, marginTop: 2 }}>⚠ {c.heterogeneity} between cohorts</div>}
                </div>
              ))}
            </div>
            <div>
              <SecH t={t}>Rejected<Count n={rejected.length} color={t.rejected} /></SecH>
              {rejected.length === 0 && <div style={{ fontSize: 12, color: t.textMuted }}>None.</div>}
              {rejected.map((c) => (
                <div key={c.id} style={{ fontSize: 12, color: t.textSecondary, marginBottom: 8, lineHeight: 1.5 }}>
                  <Id t={t}>{c.id}</Id> {c.statement}
                  <div style={{ fontSize: 10.5, color: t.textMuted, marginTop: 2 }}>fails replication · {c.replication.filter((r) => r.status === "ok").length}/{c.replication.length} cohorts</div>
                </div>
              ))}
            </div>
          </section>

          {/* translational */}
          {withTrans.length > 0 && (
            <section style={{ marginBottom: 26 }}>
              <SecH t={t}>Translational annotation</SecH>
              <p style={{ margin: "0 0 10px", fontSize: 11, color: t.textFaint, fontStyle: "italic" }}>Linked for orientation only — not part of the evidence that confirmed the findings.</p>
              {withTrans.map((c) => (
                <div key={c.id} style={{ display: "flex", gap: 8, alignItems: "baseline", marginBottom: 8 }}>
                  <Id t={t}>{c.id}</Id>
                  <div style={{ display: "flex", flexWrap: "wrap", gap: 5 }}>
                    {[...(c.translational.targets || []), ...(c.translational.trials || [])].map((x) => (
                      <span key={x} style={{ fontFamily: FONT_MONO, fontSize: 10.5, color: t.textSecondary, border: `1px solid ${t.border}`, borderRadius: RADII.sm, padding: "2px 7px", background: t.cardBg }}>{x}</span>
                    ))}
                  </div>
                </div>
              ))}
            </section>
          )}

          {/* provenance */}
          <section>
            <SecH t={t}>Provenance</SecH>
            {datasets.map((d) => (
              <div key={d.id || d.name} style={{ display: "flex", gap: 10, alignItems: "baseline", fontSize: 12, color: t.textSecondary, marginBottom: 5 }}>
                <span style={{ flex: 1 }}>{d.name}</span>
                <span style={{ fontFamily: FONT_MONO, fontSize: 11, color: t.textMuted }}>{d.sample_count} samples · {d.gene_count} genes</span>
              </div>
            ))}
            <div style={{ fontSize: 11.5, color: t.textMuted, marginTop: 8, lineHeight: 1.5 }}>
              <b>methods</b> · MWU + BH-FDR &lt; 0.05 · random-effects meta-analysis (I²/τ²) · evidence gate ≥ 2 cohorts, ≥ 2 orthogonal method families
            </div>
          </section>
        </div>
      </div>
    </div>
  );
}
